### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [wulfeku3/project7#1]
I broke it. :cry: It looks like when I try to submit a blank form, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid a blank form being submitted.

Also, It looks like some of the form inputs are resetting each time the form submits, while it's specified in the project criteria that `every form field should always show the current parameters`. [This example](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) may help you figure out how you can fix this problem.

Let me know when it's updated and I'll take another look.

**Comment by wulfeku3** [comment]
Fixed it! Thanks for the help.

**Comment by chrisvfritz** [comment]
:+1: Marvelous! So much bootstrappy goodness too! :smiley:
